
version: 2

models:
  - name: dim_orders_m
    description: "Information per order"

  - name: dim_users
    description: "information per user"

  - name: fct_user_order
    description: "Order information on a user level"
   